### ISSUE TITLE
Requires scikit-image==0.14.2

### ISSUE THREAD

**Issue by genekogan** [microsoft/CoCosNet#1]
After installing the requirements, I received `ImportError: cannot import name '_validate_lengths'` upon importing `skimage` somewhere in the testing script. I found [this scikit-image issue](https://github.com/numpy/numpy/issues/12744) which says it's fixed in version 0.14.2. After upgrading scikit-image to 0.14.2, the issue disappears.

**Comment by zhangmozhe** [comment]
Hi, Thanks for your feedback. We've fixed the requirement lists. Many Thanks!

**Comment by panzhang0212** [comment]
skimage is used to extract canny edge for celebaq(edge to face). Some scikit-image version will get black output when using skimage .feature.canny(). So if you use other version, please make sure correct output of skimage .feature.canny().
